apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
{{ include "consumer.labels" . | indent 4 }}
spec:
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
{{ include "consumer.selectorLabels" . | indent 4 }}
