apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
{{ include "producer.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "producer.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "producer.labels" . | indent 8 }}
    spec:
      containers:
        - name: server
          image: padok.fr/producer:{{ .Values.version }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
