apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
{{ include "producer.labels" . | indent 4 }}
spec:
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
{{ include "producer.selectorLabels" . | indent 4 }}
