apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
{{ include "consumer.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "consumer.fullname" . }}
  minReplicas: 0
  maxReplicas: 20
  metrics:
    - type: Object
      object:
        metric:
          name: redis_items_in_queue
          selector:
            matchLabels:
              key: padok
        describedObject:
          apiVersion: v1
          kind: Service
          name: prometheus-redis-exporter
        target:
          type: Value
          averageValue: 20
